window.publicURL = document.getElementById('publicUrl').getAttribute('content');

var appconfig = {
    LOG_LEVEL : {
        default:'ERROR',
        application:'ERROR',
        framework:'ERROR',
        services:'ERROR',
        state:'ERROR',
    },
    host: '',
    contextroot: window.publicURL,
    environment: 'SYSTEMS v1.0',
    contentManagerURL: window.publicURL + 'WcmKeys/',
    referenceTableURL: window.publicURL + 'RefTables/',
    contentManagerEndpoint: window.publicURL + 'WcmKeys/',
    communicationPreferenceService: '/dataexchange',
    caseDetailsService: '/dataexchange',
    appointmentsService: '/appointments',
    noticesService: '/dataexchange',
    announcementsAndDisasterServices: '/home',
    ssadashboardservice: '/ssadashboard',
    captchaServices: '/captcha',
    apiTimeout: 15000,
    serviceEndpoint: '/',
    restServiceHost: '/',
    loginservice: '/',
    amieligibleServiceEndpoint: '/',
    messageTableServiceEndpoint: '/messageService',
    referenceTableEndpoint: '/intransit/referencetable',
    financialinfo: '/financialinfo',
    nonfinancialinfo: '/nonfinancialinfo',
    hhdemographics: '/hhdemographics',
    auditLoggingEndpoint: '/intransit/',
    workerPortalEndpoint: '/',
    dashboard: '/document',
    accountmanagement: '/accountmanagement',
    AccountSettingUser: '/dataexchange',
    buildNumber: 1,
    buildTimestamp: '2021-03-29 23:59',
    ebtService: '/cardholders',
    forgerockRedirectURI: 'https://benefitscal.com/',
    logoutUrl: 'oauth2/realms/root/realms/customer/connect/endSession',
    officeMapping: '/dataexchangeproxy',
    staffListEndpoint: '/dataexchange',
    CreateCBOAccountService: '/dataexchangeproxy',
    applicationDetailsService: '/cboDashboardApplications',
    surveyService: '/surveys',
    chatBotUrl: 'https://daghqzwjxmect.cloudfront.net',
    liveChat: 'https://chat.cctprd.aws.calsaws.net/chat.html',
    callMe: 'https://callme.callcenter.calsaws.net/callme.html',
    adminContent: 'https://benefitscal.com/admin-content/',
    passwordService: '/dataexchangeproxy',
    admin: 'https://benefitscal.com',
    notificationService: '/notification',
    appSummaryService: '/appsummary',
    intransitLoggingEndpoint: '/intransit/',
    defaultHttpHeaders: {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        Pragma: 'no-cache',
    },
    noticeUpdater: '/notices',
    errorLoggingEndPoint: '/sqsproxy/v1/enqueue',
    errorLogFlag: true,
    chatBotMinFile: "https://daghqzwjxmect.cloudfront.net/lex-web-ui-loader.min.js",
    chatBotEnabled: true,
    logRocketFlag: false,
    logRocketUrl: '',
    prdstgenv: 'prd',
    includeUtm: true,
    includeReferrer: true,
    ACLEndpoint: '/common/',
    RedirectDomains: ["/ybn", "/c4yourself"],
    RedirectPastedUrls: ['/ApplyForBenefits', '/Appointments', '/Admin', '/CBO', '/SupportRequest', '/DocumentUpload'],
    RedirectCBOReferalUrls: ['/r'],
    chatbotVoiceFlag: true,
    chatbotVoiceChineseFlag: false,
    chatbotVoiceJapaneseFlag: false,
    chatbotVoiceKoreanFlag: false,
    accessService: '/validateAccessKey',
    intransitEndPoint: '/intransitEndPoint/v2/',
    S3UPLOAD_RETRY_LIMIT: 2,
    EnableConsentPage: false,
    enableENotification: true,
    callMeLowerEnvFlag: false,
    CountyPreferencesEnabled: true,
    enablePasswordProtectedValidation: true,
    MailAdrressValidationEnabled: true,
    MailAdrressValidationMonths: 3,
    enablePreDocUploadBucket: true,
    globalSearch: '/globalsearch',
    CaseLinkBannerDisableFlag: true,
    isROIEnabled: false,
    enableCaseLinking: true,
    isDisasterModeOn: false,
    enableHistoryLink: true,
    enablePhoneNumFlag: true,
    isTCFormsDisplay: false,
    isTimeClockEnabled: false,
    EnableConsentSSAPage: true,
    enableDCF385: true,
    enableEBT2259SeqApi: true,
    enableEBTPdfSeqApi: true,
    enableHelpABAWD: true,
    enableDashboardABAWD: true,
    enableSRABAWD : true,
    enableCF37ABAWD: true,
    enableAFBABAWD: true,
    isMultiDocActive : true,
    isMultiDocForCboAnonActive: true,
    showDocReceiptDate: '07/25/2024 20:00',
    buildVersion: '26.06.01',
};